bgnorm = "#000000"
bgsel = "#000000"
wsbgnorm = "#121212"

height = 34
fontname = "MonaspiceNE NFP"
fontsize = 15
margin = 6
margin-vertical = 6
lrpad = 2

padding = 12
module-radius = 14

workspace-lrpad = 8
workspace-padding = 16
workspacepx = 6
workspaceselw = 28
workspaceselh = 8

# Syntax:
# module = { name, command, interval, signal, position }

# update modules: pkill -RTMIN+<signal> ambar
# ex: signal = 3, then pkill -35 ambar updates the module

# Modules Left
module = { "clock", "sb-clock", 1, 2, left }

# Modules Center
module = { "workspaces", 0, 0, 1, right }

# Modules Right
module = { "battery", "sb-battery2", 5, 3, right }
module = { "volume", "sb-volume2", 0, 10, right }
module = { "wifi", "sb-internet", 0, 11, right }
module = { "dmenu", "sb-dmenu", 0, 20, right }
#module = { "wifi", "sb-cpubars", 1, 12, right }
